# vim: set ft=make :

# Small hint on assignments:

VAR = $(OTHERVAR) # is evaluated when used,
VAR := $(OTHERVAR) # is evaluated immediately.

#HTMLDIR = $(subst $(ORGMODE),$(HTML),$(PWD))

#EMACS_PRE_FLAGS = --batch -l $(ORGMODE)/config.el --visit
#EMACS_PRE_FLAGS = -u "$(USER)" --batch --eval '(load user-init-file)' --visit

 $(ORGMODE)/include/menu.org
